# POST  http://localhost:5000/api/login
# Content-Type: application/json

# {
#     "credential": "pepepe",
#     "password": "Alung01042003#1"
# }

GET http://localhost:5000/api/history/update


 
# GET http://localhost:5000/api/users/20

# PATCH   http://localhost:5000/api/users/15
# Content-Type: application/json

# {
#     "nama": "sun god nia",
#     "password": "alung01042003"
# }

# DELETE http://localhost:5000/api/users/100


# POST  http://localhost:5000/api/register
# Content-Type: application/json

# {
#     "nama": "alung",
#     "email": "alusngpwd@gmail.com",
#     "password": "asdasdasd",
#     "confirmPassword": "asdasdasd"
# }

GET http://localhost:5000/api/profile/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTcyMzQ3ODM1NywiZXhwIjoxNzIzNDc4NDE3fQ.Dw46-FYQ0Ke6yDyDuhQifQFdScE2Bi9cYpz7wEo1kko
Content-Type: application/json


# $2b$10$bw89PAvgoVSCCThxxiLm4OwqakZrJT7KsIlFvDi03YhDtYrsbl6he
# $2b$10$yPBITrUnWnniAi9TnBvS.uJvh3HWCPNDzK0oayCRf1TyLhc4oELTm
# POST http://localhost:5000/api/dongeng
# Content-Type: multipart/form-data

# {
#     "title": "oke"
# }